### ISSUE TITLE
Removing click from commands

### ISSUE THREAD

**Issue by avinash-oza** [tbumi/glacier-upload#15]
Hi,

I am not sure if I should have the discussion here so sorry in advance. Would it be possible to expose the available functions without click? For example, I would like to use the API you have created to write a snippet as the following:

```python
from glacier_upload.upload import upload

upload(...)
```

However, when I currently do this within a python console I receive an issue about the number of arguments. Reading online I found an answer like: https://stackoverflow.com/a/40094408 which may allow both usages as the functions are straightforward.

An example similar to the link would be

```python

# click decorators here
def upload_command(...):
    upload(...) # call the original upload here

def upload(...):
    # stays as it currently is but implements the functionality
```

Let me know your thoughts on this as I would be interested in submitting a pull request for this. My further use case would be having upload() return back the response metadata to store the archive id myself but that will be for another issue.

Great work BTW.

**Comment by tbumi** [comment]
Hi @avinash-oza ! I'm so sorry I missed the notification for this issue (and pull request, until you mentioned me)
Anyways, this is a great idea. I never imagined my script will be used as a kind of library, but I guess I have no objections right now.

**Comment by avinash-oza** [comment]
I was looking for code online that I could use in order to upload big archives. It seemed that your code had all of that ready except I could not get back the multipart upload id if my upload had failed. 

his was to lay the groundwork for another (hopefully soon) pull request that would return this id in an exception if the upload failed. The use case is over here: https://github.com/avinash-oza/home-projects/blob/master/glacier-testing/glacier_script.py

where I am using your script along with the archive ids returned to keep my own db in S3 of what I have uploaded.
