### ISSUE TITLE
Reattempt failed upload part instead of crashing immediately

### ISSUE THREAD

**Issue by azeemba** [tbumi/glacier-upload#2]
Looks like my upload failed due to a RequestTimeout. If I start the upload again, it does properly check what parts have already been uploaded but it takes a lot of time.

I made some changes locally to make this work, wanted to check if there was interest before sending a PR.

**Comment by tbumi** [comment]
Thanks for submitting the issue @azeemba! Your contributions are very welcome. Feel free to submit a PR with your changes.
