### ISSUE TITLE
Function import name mismatch

### ISSUE THREAD

**Issue by JCMarques15** [tbumi/glacier-upload#33]
Hi, when trying to abort a glacier multipart upload I get the following error:

$abort_glacier_upload --help
Traceback (most recent call last):
  File "/****/****/.local/share/virtualenvs/Glacier-Backups-Tool-UR0ryj4F/bin/abort_glacier_upload", line 5, in <module>
    from glacier_upload.abort_upload import abort_upload
ModuleNotFoundError: No module named 'glacier_upload.abort_upload'

This has 1 of two easy fixes:
1 - change the module file name to match: "manual_abort_upload.py" > "abort_upload.py"
or
2 - change the import to match the module file name: "from glacier_upload.abort_upload import abort_upload" > " from glacier_upload.manual_abort_upload import abort_upload"

I hope this helps 😃

**Comment by tbumi** [comment]
Hi, version 2.0 has this function removed. If you want to delete a multipart upload in progress, please use the [AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/glacier/abort-multipart-upload.html).
