### ISSUE TITLE
PIP version actualization

### ISSUE THREAD

**Issue by AJIOB** [tbumi/glacier-upload#34]
Is [pip version](https://pypi.org/project/glacier_upload/#history) will be actualized with fixes from the develop branch (such as MR #26)?

In what period of time it will be available?

**Comment by tbumi** [comment]
Sorry for the long time absent. I've released [version 2.0](https://pypi.org/project/glacier-upload/2.0/) of this package. Feel free to open issues/PRs for any bugs you find.
